use caps::Capability;
use libc::{self, c_long};

pub const CAPS: &[Capability] = &[
    Capability::CAP_SETPCAP,
    Capability::CAP_MKNOD,
    Capability::CAP_AUDIT_WRITE,
    Capability::CAP_CHOWN,
    Capability::CAP_NET_RAW,
    Capability::CAP_DAC_OVERRIDE,
    Capability::CAP_FOWNER,
    Capability::CAP_FSETID,
    Capability::CAP_KILL,
    Capability::CAP_SETGID,
    Capability::CAP_SETUID,
    Capability::CAP_NET_BIND_SERVICE,
    Capability::CAP_SYS_CHROOT,
    Capability::CAP_SETFCAP,
];

pub const SYSCALLS: [c_long; 283] = [
    libc::SYS_accept,
    libc::SYS_accept4,
    libc::SYS_access,
    libc::SYS_adjtimex,
    libc::SYS_alarm,
    libc::SYS_bind,
    libc::SYS_brk,
    libc::SYS_capget,
    libc::SYS_capset,
    libc::SYS_chdir,
    libc::SYS_chmod,
    libc::SYS_chown,
    // libc::SYS_chown32,
    libc::SYS_clock_getres,
    // libc::SYS_clock_getres_time64,
    libc::SYS_clock_gettime,
    // libc::SYS_clock_gettime64,
    libc::SYS_clock_nanosleep,
    // libc::SYS_clock_nanosleep_time64,
    libc::SYS_close,
    libc::SYS_connect,
    libc::SYS_copy_file_range,
    libc::SYS_creat,
    libc::SYS_dup,
    libc::SYS_dup2,
    libc::SYS_dup3,
    libc::SYS_epoll_create,
    libc::SYS_epoll_create1,
    libc::SYS_epoll_ctl,
    libc::SYS_epoll_ctl_old,
    libc::SYS_epoll_pwait,
    libc::SYS_epoll_wait,
    libc::SYS_epoll_wait_old,
    libc::SYS_eventfd,
    libc::SYS_eventfd2,
    libc::SYS_execve,
    libc::SYS_execveat,
    libc::SYS_exit,
    libc::SYS_exit_group,
    libc::SYS_faccessat,
    libc::SYS_fadvise64,
    // libc::SYS_fadvise64_64,
    libc::SYS_fallocate,
    libc::SYS_fanotify_mark,
    libc::SYS_fchdir,
    libc::SYS_fchmod,
    libc::SYS_fchmodat,
    libc::SYS_fchown,
    // libc::SYS_fchown32,
    libc::SYS_fchownat,
    libc::SYS_fcntl,
    // libc::SYS_fcntl64,
    libc::SYS_fdatasync,
    libc::SYS_fgetxattr,
    libc::SYS_flistxattr,
    libc::SYS_flock,
    libc::SYS_fork,
    libc::SYS_fremovexattr,
    libc::SYS_fsetxattr,
    libc::SYS_fstat,
    // libc::SYS_fstat64,
    // libc::SYS_fstatat64,
    libc::SYS_fstatfs,
    // libc::SYS_fstatfs64,
    libc::SYS_fsync,
    libc::SYS_ftruncate,
    // libc::SYS_ftruncate64,
    libc::SYS_futex,
    // libc::SYS_futex_time64,
    libc::SYS_futimesat,
    libc::SYS_getcpu,
    libc::SYS_getcwd,
    libc::SYS_getdents,
    libc::SYS_getdents64,
    libc::SYS_getegid,
    // libc::SYS_getegid32,
    libc::SYS_geteuid,
    // libc::SYS_geteuid32,
    libc::SYS_getgid,
    // libc::SYS_getgid32,
    libc::SYS_getgroups,
    // libc::SYS_getgroups32,
    libc::SYS_getitimer,
    libc::SYS_getpeername,
    libc::SYS_getpgid,
    libc::SYS_getpgrp,
    libc::SYS_getpid,
    libc::SYS_getppid,
    libc::SYS_getpriority,
    libc::SYS_getrandom,
    libc::SYS_getresgid,
    // libc::SYS_getresgid32,
    libc::SYS_getresuid,
    // libc::SYS_getresuid32,
    libc::SYS_getrlimit,
    libc::SYS_get_robust_list,
    libc::SYS_getrusage,
    libc::SYS_getsid,
    libc::SYS_getsockname,
    libc::SYS_getsockopt,
    libc::SYS_get_thread_area,
    libc::SYS_gettid,
    libc::SYS_gettimeofday,
    libc::SYS_getuid,
    // libc::SYS_getuid32,
    libc::SYS_getxattr,
    libc::SYS_inotify_add_watch,
    libc::SYS_inotify_init,
    libc::SYS_inotify_init1,
    libc::SYS_inotify_rm_watch,
    libc::SYS_io_cancel,
    libc::SYS_ioctl,
    libc::SYS_io_destroy,
    libc::SYS_io_getevents,
    // libc::SYS_io_pgetevents,
    // libc::SYS_io_pgetevents_time64,
    libc::SYS_ioprio_get,
    libc::SYS_ioprio_set,
    libc::SYS_io_setup,
    libc::SYS_io_submit,
    // libc::SYS_io_uring_enter,
    // libc::SYS_io_uring_register,
    // libc::SYS_io_uring_setup,
    // libc::SYS_ipc,
    libc::SYS_kill,
    libc::SYS_lchown,
    // libc::SYS_lchown32,
    libc::SYS_lgetxattr,
    libc::SYS_link,
    libc::SYS_linkat,
    libc::SYS_listen,
    libc::SYS_listxattr,
    libc::SYS_llistxattr,
    // libc::SYS__llseek,
    libc::SYS_lremovexattr,
    libc::SYS_lseek,
    libc::SYS_lsetxattr,
    libc::SYS_lstat,
    // libc::SYS_lstat64,
    libc::SYS_madvise,
    libc::SYS_memfd_create,
    libc::SYS_mincore,
    libc::SYS_mkdir,
    libc::SYS_mkdirat,
    libc::SYS_mknod,
    libc::SYS_mknodat,
    libc::SYS_mlock,
    libc::SYS_mlock2,
    libc::SYS_mlockall,
    libc::SYS_mmap,
    // libc::SYS_mmap2,
    libc::SYS_mprotect,
    libc::SYS_mq_getsetattr,
    libc::SYS_mq_notify,
    libc::SYS_mq_open,
    libc::SYS_mq_timedreceive,
    // libc::SYS_mq_timedreceive_time64,
    libc::SYS_mq_timedsend,
    // libc::SYS_mq_timedsend_time64,
    libc::SYS_mq_unlink,
    libc::SYS_mremap,
    libc::SYS_msgctl,
    libc::SYS_msgget,
    libc::SYS_msgrcv,
    libc::SYS_msgsnd,
    libc::SYS_msync,
    libc::SYS_munlock,
    libc::SYS_munlockall,
    libc::SYS_munmap,
    libc::SYS_nanosleep,
    libc::SYS_newfstatat,
    // libc::SYS__newselect,
    libc::SYS_open,
    libc::SYS_openat,
    libc::SYS_pause,
    libc::SYS_pipe,
    libc::SYS_pipe2,
    libc::SYS_poll,
    libc::SYS_ppoll,
    // libc::SYS_ppoll_time64,
    libc::SYS_prctl,
    libc::SYS_pread64,
    libc::SYS_preadv,
    libc::SYS_preadv2,
    libc::SYS_prlimit64,
    libc::SYS_pselect6,
    // libc::SYS_pselect6_time64,
    libc::SYS_pwrite64,
    libc::SYS_pwritev,
    libc::SYS_pwritev2,
    libc::SYS_read,
    libc::SYS_readahead,
    libc::SYS_readlink,
    libc::SYS_readlinkat,
    libc::SYS_readv,
    // libc::SYS_recv,
    libc::SYS_recvfrom,
    libc::SYS_recvmmsg,
    // libc::SYS_recvmmsg_time64,
    libc::SYS_recvmsg,
    libc::SYS_remap_file_pages,
    libc::SYS_removexattr,
    libc::SYS_rename,
    libc::SYS_renameat,
    libc::SYS_renameat2,
    libc::SYS_restart_syscall,
    libc::SYS_rmdir,
    libc::SYS_rt_sigaction,
    libc::SYS_rt_sigpending,
    libc::SYS_rt_sigprocmask,
    libc::SYS_rt_sigqueueinfo,
    libc::SYS_rt_sigreturn,
    libc::SYS_rt_sigsuspend,
    libc::SYS_rt_sigtimedwait,
    // libc::SYS_rt_sigtimedwait_time64,
    libc::SYS_rt_tgsigqueueinfo,
    libc::SYS_sched_getaffinity,
    libc::SYS_sched_getattr,
    libc::SYS_sched_getparam,
    libc::SYS_sched_get_priority_max,
    libc::SYS_sched_get_priority_min,
    libc::SYS_sched_getscheduler,
    libc::SYS_sched_rr_get_interval,
    // libc::SYS_sched_rr_get_interval_time64,
    libc::SYS_sched_setaffinity,
    libc::SYS_sched_setattr,
    libc::SYS_sched_setparam,
    libc::SYS_sched_setscheduler,
    libc::SYS_sched_yield,
    libc::SYS_seccomp,
    libc::SYS_select,
    libc::SYS_semctl,
    libc::SYS_semget,
    libc::SYS_semop,
    libc::SYS_semtimedop,
    // libc::SYS_semtimedop_time64,
    // libc::SYS_send,
    libc::SYS_sendfile,
    // libc::SYS_sendfile64,
    libc::SYS_sendmmsg,
    libc::SYS_sendmsg,
    libc::SYS_sendto,
    libc::SYS_setfsgid,
    // libc::SYS_setfsgid32,
    libc::SYS_setfsuid,
    // libc::SYS_setfsuid32,
    libc::SYS_setgid,
    // libc::SYS_setgid32,
    libc::SYS_setgroups,
    // libc::SYS_setgroups32,
    libc::SYS_setitimer,
    libc::SYS_setpgid,
    libc::SYS_setpriority,
    libc::SYS_setregid,
    // libc::SYS_setregid32,
    libc::SYS_setresgid,
    // libc::SYS_setresgid32,
    libc::SYS_setresuid,
    // libc::SYS_setresuid32,
    libc::SYS_setreuid,
    // libc::SYS_setreuid32,
    libc::SYS_setrlimit,
    libc::SYS_set_robust_list,
    libc::SYS_setsid,
    libc::SYS_setsockopt,
    libc::SYS_set_thread_area,
    libc::SYS_set_tid_address,
    libc::SYS_setuid,
    // libc::SYS_setuid32,
    libc::SYS_setxattr,
    libc::SYS_shmat,
    libc::SYS_shmctl,
    libc::SYS_shmdt,
    libc::SYS_shmget,
    libc::SYS_shutdown,
    libc::SYS_sigaltstack,
    libc::SYS_signalfd,
    libc::SYS_signalfd4,
    // libc::SYS_sigprocmask,
    // libc::SYS_sigreturn,
    libc::SYS_socket,
    // libc::SYS_socketcall,
    libc::SYS_socketpair,
    libc::SYS_splice,
    libc::SYS_stat,
    // libc::SYS_stat64,
    libc::SYS_statfs,
    // libc::SYS_statfs64,
    libc::SYS_statx,
    libc::SYS_symlink,
    libc::SYS_symlinkat,
    libc::SYS_sync,
    libc::SYS_sync_file_range,
    libc::SYS_syncfs,
    libc::SYS_sysinfo,
    libc::SYS_tee,
    libc::SYS_tgkill,
    libc::SYS_time,
    libc::SYS_timer_create,
    libc::SYS_timer_delete,
    libc::SYS_timer_getoverrun,
    libc::SYS_timer_gettime,
    // libc::SYS_timer_gettime64,
    libc::SYS_timer_settime,
    // libc::SYS_timer_settime64,
    libc::SYS_timerfd_create,
    libc::SYS_timerfd_gettime,
    // libc::SYS_timerfd_gettime64,
    libc::SYS_timerfd_settime,
    // libc::SYS_timerfd_settime64,
    libc::SYS_times,
    libc::SYS_tkill,
    libc::SYS_truncate,
    // libc::SYS_truncate64,
    // libc::SYS_ugetrlimit,
    libc::SYS_umask,
    libc::SYS_uname,
    libc::SYS_unlink,
    libc::SYS_unlinkat,
    libc::SYS_utime,
    libc::SYS_utimensat,
    // libc::SYS_utimensat_time64,
    libc::SYS_utimes,
    libc::SYS_vfork,
    libc::SYS_vmsplice,
    libc::SYS_wait4,
    libc::SYS_waitid,
    // libc::SYS_waitpid,
    libc::SYS_write,
    libc::SYS_writev,
    libc::SYS_arch_prctl,
    libc::SYS_modify_ldt,
    libc::SYS_bpf,
    libc::SYS_clone,
    libc::SYS_fanotify_init,
    libc::SYS_lookup_dcookie,
    libc::SYS_mount,
    libc::SYS_name_to_handle_at,
    libc::SYS_perf_event_open,
    libc::SYS_quotactl,
    libc::SYS_setdomainname,
    libc::SYS_sethostname,
    libc::SYS_setns,
    libc::SYS_syslog,
    // libc::SYS_umount,
    libc::SYS_umount2,
    libc::SYS_unshare,
];
